version: '3.8'
services:
  gallery:
    build: .
    container_name: kai_multimedia_gallery
    depends_on:
      - redis
    ports:
      - "3000:3000"
    volumes:
      - ./public/media:/app/public/media
    restart: always
    networks:
      - default
      - shared_net

  redis:
    image: redis:alpine
    container_name: gallery_db
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: always
    networks:
      - default
      - shared_net

volumes:
  redis-data:

networks:
  shared_net:
    name: bancamp-net
    external: trueroot@ubuntu-4gb-nbg1-1:/var/docker/kai-gallery# ls
